# Generated by Django 4.0.4 on 2022-05-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0003_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('1', 'published'), ('2', 'draft')], default=1, max_length=50),
        ),
    ]
