# Generated by Django 4.0.4 on 2022-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0006_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(default=1),
        ),
    ]
