# Generated by Django 4.0.4 on 2022-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0010_alter_article_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='durasi',
            field=models.DateField(),
        ),
    ]
